apiVersion: batch/v1
kind: CronJob
metadata:
  name: condor-worker-cleaner
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: client_group
                    operator: Exists  # Ensures that the job runs on nodes with the label, regardless of its value
          containers:
          - name: condor-worker-cleaner
            image: ghcr.io/kbase-infra/condor-worker-cleaner:main
            volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
          volumes:
          - name: docker-socket
            hostPath:
              path: /var/run/docker.sock
              type: Socket
