apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: condor-worker-cleaner
spec:
  selector:
    matchLabels:
      app: condor-worker-cleaner
  template:
    metadata:
      labels:
        app: condor-worker-cleaner
    spec:
      hostPID: true # Grants full privileges to the container to see PIDs
      hostNetwork: true  # Enables host networking because can't resolve DNS on condor hosts for some reason
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: client_group
                operator: Exists
      tolerations:
      - key: "condor_worker"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: condor-worker-cleaner
        image: ghcr.io/kbase-infra/condor-worker-cleaner:main
        env:
        - name: SLACK_WEBHOOK_URL
          value: "<your-slack-webhook-url>"
        securityContext:
          privileged: true  # Grants full privileges to the container
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
